message: This is a message defined in the config.yaml.
messageRepititions: 3
database:
   driverClass: org.postgresql.Driver
   user: phonebookuser
   password: phonebookpassword
   url: jdbc:postgresql://localhost/phonebook
   properties:
      charSet: UTF-8
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect